name: Secret Scanning
on: [push, pull_request]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: "" # Scan all history for the first run / independent scan
          head: HEAD
          extra_args: --debug
      - name: Alert on Failure
        if: failure()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          pip install requests python-dotenv
          trufflehog git file://./ --extra-args "--debug" --json > results.json 2>&1 || true
          if [ -s results.json ]; then
             pip install requests python-dotenv
             python notifier.py --ci --input results.json
          fi
